index:
   path: /
   methods: [GET]
   controller: App\Controller\DefaultController::index

api_login_check:
   path: /api/login_check
   methods:  [POST]

not_found:
   path: /{path}
   controller: App\Controller\DefaultController::notFound
   requirements:
      path: .*
