index:
   path: /
   methods: [GET]
   controller: App\Controller\DefaultController::index

api_login_check:
   path: /api/login_check
   methods:  [POST]

api_affiliate_create:
   path: /api/affiliates
   controller: App\Action\AffiliateCreateAction
   methods: [POST]

api_affiliate_list:
   path: /api/affiliates
   methods: [GET]
   controller: App\Action\AffiliateListAction

api_affiliate_get:
   path: /api/affiliates/{id}
   methods: [GET]
   controller: App\Action\AffiliateGetAction

not_found:
   path: /{path}
   controller: App\Controller\DefaultController::notFound
   requirements:
      path: .*
